name: 'Setup and Build .net'
description: 'Setup .net core min v2 or the latest and build resources'
runs:
  using: 'composite'
  steps:
    - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'
    - name: build code
      run: dotnet build BlogApi.csproj
      shell: bash