name: First Workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Setup and build .net
        uses: ./.github/actions/quickbuild
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: bin/Debug/net7.0
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Check code version
        run: dotnet --info
      - name: Test code
        run: dotnet test BlogApi.csproj
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bin
      - name: List contents
        run: ls -l
        
